// Pregenerate a voice profile's BACKCHANNELS — the short listening noises ("Mhm.") a character makes
// while the learner is talking to them.
//
// A backchannel is not a dialogue node. It belongs to the VOICE, not to any one tree: the same "Mhm."
// serves every scene that character appears in, and it has to be ready to fire the instant the learner
// stops speaking — before any processing could possibly return. So it is declared on the voice profile
// (server/catalog/voices.json → profiles.<id>.backchannels) and pregenerated here.
//
// Same content-addressed store, same key, same preflight as build:dialogue-assets — the key is
// (provider, voiceTag, text), so a surface plays one with the ordinary
// `/api/speak?text=Mhm.&voice=slavko` and gets the pregenerated bytes for free.
//
//   npm run build:backchannels                 # every profile that declares backchannels
//   npm run build:backchannels -- slavko       # just this profile
//   npm run build:backchannels -- slavko --regen

import "dotenv/config";
import { getE3 } from "../adapters/index";
import * as store from "../assets/store";
import { CATALOG } from "../catalog";

const args = process.argv.slice(2);
const regen = args.includes("--regen");
const onlyProfile = args.find((a) => !a.startsWith("--"));

const profiles = Object.values(CATALOG.voiceProfiles)
  .filter((p) => p.backchannels?.length)
  .filter((p) => onlyProfile === undefined || p.id === onlyProfile);

if (!profiles.length) {
  const declared = Object.values(CATALOG.voiceProfiles).filter((p) => p.backchannels?.length).map((p) => p.id);
  console.error(
    onlyProfile
      ? `Voice profile "${onlyProfile}" declares no backchannels. Declared by: ${declared.join(", ") || "(none)"}.`
      : `No voice profile declares backchannels — add them to server/catalog/voices.json.`,
  );
  process.exit(1);
}

const e3 = getE3();

// Same preflight as build:dialogue-assets — synthesis is billed, so verify every binding resolves and
// fail fast listing all problems, rather than discovering a missing one mid-run.
{
  const problems: string[] = [];
  for (const p of profiles) {
    let voiceId = "";
    try {
      voiceId = e3.voiceTagFor(p.id).split(":")[0] ?? "";
    } catch (err: any) {
      problems.push(`voice profile "${p.id}": ${err?.message}`);
      continue;
    }
    if (!voiceId) problems.push(`voice profile "${p.id}": no voice id configured — set its env binding (see docs/SECRETS.md)`);
  }
  if (e3.name === "elevenlabs" && !process.env.ELEVENLABS_API_KEY) problems.push(`ELEVENLABS_API_KEY is not set (see docs/SECRETS.md)`);
  if (problems.length) {
    console.error(`\n❌ preflight failed — nothing synthesized:`);
    for (const p of problems) console.error(`   • ${p}`);
    console.error(`\n   Set the missing binding(s) in .env, then re-run. This build is idempotent — built clips are free.\n`);
    process.exit(1);
  }
  console.log(`\n✓ preflight ok — ${profiles.length} voice profile(s): ${profiles.map((p) => p.id).join(", ")}`);
}

let hits = 0, made = 0, failures = 0;

for (const p of profiles) {
  const voiceTag = e3.voiceTagFor(p.id);
  console.log(`\n▶ ${p.id}  e3=${e3.name}  ${p.backchannels!.length} backchannel(s)`);
  for (const text of p.backchannels!) {
    const key = store.audioKey(e3.name, voiceTag, text);
    if (regen) store.remove(key, "audio");
    try {
      const { hit } = await store.getOrCreate(
        key,
        "audio",
        { provider: e3.name, voiceOrModel: voiceTag, text, objectiveId: `backchannel:${p.id}` },
        async () => {
          const r = await e3.synthesize({ text, voiceProfile: p.id });
          return { bytes: Buffer.from(r.audioBase64, "base64"), mimeType: r.mimeType };
        },
      );
      hit ? hits++ : made++;
      console.log(`   ${hit ? "hit " : "gen "} ${key.slice(0, 10)}…  "${text}"`);
    } catch (err: any) {
      failures++;
      console.log(`   ❌  "${text}": ${err?.message}`);
    }
  }
}

console.log(`\nDone. ${made} generated, ${hits} reused (free)` + (failures ? `, ${failures} failed.` : "."));
process.exit(failures > 0 ? 1 : 0);
